package GCalendarInterpreter.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Colours extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Colours() {
    super(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee62L, "Colours", "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388962");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Tomate_0 = new EnumerationDescriptor.MemberDescriptor("Tomate", "tomate", 0x5ee948073c4bee64L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388964");
  private final EnumerationDescriptor.MemberDescriptor myMember_Mandarina_0 = new EnumerationDescriptor.MemberDescriptor("Mandarina", "mandaria", 0x5ee948073c4bee63L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388963");
  private final EnumerationDescriptor.MemberDescriptor myMember_Salvia_0 = new EnumerationDescriptor.MemberDescriptor("Salvia", "salvia", 0x5ee948073c4bee66L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388966");
  private final EnumerationDescriptor.MemberDescriptor myMember_PavoReal_0 = new EnumerationDescriptor.MemberDescriptor("PavoReal", "pavoreal", 0x5ee948073c4bee67L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388967");
  private final EnumerationDescriptor.MemberDescriptor myMember_Lavanda_0 = new EnumerationDescriptor.MemberDescriptor("Lavanda", "lavanda", 0x5ee948073c4bee69L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388969");
  private final EnumerationDescriptor.MemberDescriptor myMember_Flamenco_0 = new EnumerationDescriptor.MemberDescriptor("Flamenco", "flamenco", 0x5ee948073c4bee6aL, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388970");
  private final EnumerationDescriptor.MemberDescriptor myMember_Banana_0 = new EnumerationDescriptor.MemberDescriptor("Banana", "banana", 0x5ee948073c4bee6bL, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388971");
  private final EnumerationDescriptor.MemberDescriptor myMember_Albahaca_0 = new EnumerationDescriptor.MemberDescriptor("Albahaca", "albahaca", 0x5ee948073c4bee6cL, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388972");
  private final EnumerationDescriptor.MemberDescriptor myMember_Arandano_0 = new EnumerationDescriptor.MemberDescriptor("Arandano", "arandano", 0x5ee948073c4bee6dL, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388973");
  private final EnumerationDescriptor.MemberDescriptor myMember_Uva_0 = new EnumerationDescriptor.MemberDescriptor("Uva", "uva", 0x5ee948073c4bee6eL, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388974");
  private final EnumerationDescriptor.MemberDescriptor myMember_Grafito_0 = new EnumerationDescriptor.MemberDescriptor("Grafito", "grafito", 0x5ee948073c4bee70L, "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388976");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee62L, 0x5ee948073c4bee64L, 0x5ee948073c4bee63L, 0x5ee948073c4bee66L, 0x5ee948073c4bee67L, 0x5ee948073c4bee69L, 0x5ee948073c4bee6aL, 0x5ee948073c4bee6bL, 0x5ee948073c4bee6cL, 0x5ee948073c4bee6dL, 0x5ee948073c4bee6eL, 0x5ee948073c4bee70L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Tomate_0, myMember_Mandarina_0, myMember_Salvia_0, myMember_PavoReal_0, myMember_Lavanda_0, myMember_Flamenco_0, myMember_Banana_0, myMember_Albahaca_0, myMember_Arandano_0, myMember_Uva_0, myMember_Grafito_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_PavoReal_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Tomate":
        return myMember_Tomate_0;
      case "Mandarina":
        return myMember_Mandarina_0;
      case "Salvia":
        return myMember_Salvia_0;
      case "PavoReal":
        return myMember_PavoReal_0;
      case "Lavanda":
        return myMember_Lavanda_0;
      case "Flamenco":
        return myMember_Flamenco_0;
      case "Banana":
        return myMember_Banana_0;
      case "Albahaca":
        return myMember_Albahaca_0;
      case "Arandano":
        return myMember_Arandano_0;
      case "Uva":
        return myMember_Uva_0;
      case "Grafito":
        return myMember_Grafito_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
