package GCalendarInterpreter.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Color = 0;
  public static final int Descripcion = 1;
  public static final int Evento = 2;
  public static final int FechaFin = 3;
  public static final int FechaInicio = 4;
  public static final int ListCampos = 5;
  public static final int Titulo = 6;
  public static final int Ubicacion = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L);
    builder.put(0x5ee948073c4bed69L, Color);
    builder.put(0x5ee948073c4bee4aL, Descripcion);
    builder.put(0x5ee948073c4bed40L, Evento);
    builder.put(0x5ee948073c4bee2cL, FechaFin);
    builder.put(0x5ee948073c4bed56L, FechaInicio);
    builder.put(0x5ee948073c4bed45L, ListCampos);
    builder.put(0x5ee948073c4bed52L, Titulo);
    builder.put(0x5ee948073c4bed62L, Ubicacion);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
