package GCalendarInterpreter.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptDescripcion = createDescriptorForDescripcion();
  /*package*/ final ConceptDescriptor myConceptEvento = createDescriptorForEvento();
  /*package*/ final ConceptDescriptor myConceptFechaFin = createDescriptorForFechaFin();
  /*package*/ final ConceptDescriptor myConceptFechaInicio = createDescriptorForFechaInicio();
  /*package*/ final ConceptDescriptor myConceptListCampos = createDescriptorForListCampos();
  /*package*/ final ConceptDescriptor myConceptTitulo = createDescriptorForTitulo();
  /*package*/ final ConceptDescriptor myConceptUbicacion = createDescriptorForUbicacion();
  /*package*/ final EnumerationDescriptor myEnumerationColours = new EnumerationDescriptor_Colours();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeDate = new ConstrainedStringDatatypeDescriptorImpl(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4fcf60L, "Date", "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052643168", "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\\d{4}$");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeHour = new ConstrainedStringDatatypeDescriptorImpl(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c505587L, "Hour", "r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052677511", "^(?:[01]\\d|2[0-3]):[0-5]\\d$");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptColor, myConceptDescripcion, myConceptEvento, myConceptFechaFin, myConceptFechaInicio, myConceptListCampos, myConceptTitulo, myConceptUbicacion);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.Descripcion:
        return myConceptDescripcion;
      case LanguageConceptSwitch.Evento:
        return myConceptEvento;
      case LanguageConceptSwitch.FechaFin:
        return myConceptFechaFin;
      case LanguageConceptSwitch.FechaInicio:
        return myConceptFechaInicio;
      case LanguageConceptSwitch.ListCampos:
        return myConceptListCampos;
      case LanguageConceptSwitch.Titulo:
        return myConceptTitulo;
      case LanguageConceptSwitch.Ubicacion:
        return myConceptUbicacion;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationColours, myCSDatatypeDate, myCSDatatypeHour);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "Color", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed69L);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388713");
    b.version(3);
    b.property("colorCode", 0x5ee948073c4bed6aL).type(MetaIdFactory.dataTypeId(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee62L)).origin("6839076705052388714").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDescripcion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "Descripcion", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee4aL);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388938");
    b.version(3);
    b.property("descripcionString", 0x5ee948073c4bee4cL).type(PrimitiveTypeId.STRING).origin("6839076705052388940").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEvento() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "Evento", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed40L);
    b.class_(false, false, true);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388672");
    b.version(3);
    b.aggregate("campos", 0x5ee948073c4bed47L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed45L).optional(false).ordered(true).multiple(false).origin("6839076705052388679").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFechaFin() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "FechaFin", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee2cL);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388908");
    b.version(3);
    b.property("fechaFinDate", 0x5ee948073c4bee2eL).type(MetaIdFactory.dataTypeId(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4fcf60L)).origin("6839076705052388910").done();
    b.property("horaFin", 0x5ee948073c4bee2fL).type(MetaIdFactory.dataTypeId(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c505587L)).origin("6839076705052388911").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFechaInicio() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "FechaInicio", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed56L);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388694");
    b.version(3);
    b.property("fechaInicioDate", 0x5ee948073c4bed58L).type(MetaIdFactory.dataTypeId(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4fcf60L)).origin("6839076705052388696").done();
    b.property("horaInicio", 0x5ee948073c4bee02L).type(MetaIdFactory.dataTypeId(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c505587L)).origin("6839076705052388866").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListCampos() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "ListCampos", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed45L);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388677");
    b.version(3);
    b.aggregate("titulo", 0x5ee948073c4ec130L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed52L).optional(true).ordered(true).multiple(false).origin("6839076705052574000").done();
    b.aggregate("fechaInicio", 0x5ee948073c4f48aeL).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed56L).optional(true).ordered(true).multiple(false).origin("6839076705052608686").done();
    b.aggregate("fechaFin", 0x5ee948073c4f48b1L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee2cL).optional(true).ordered(true).multiple(false).origin("6839076705052608689").done();
    b.aggregate("ubicacion", 0x5ee948073c4f48b2L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed62L).optional(true).ordered(true).multiple(false).origin("6839076705052608690").done();
    b.aggregate("descripcion", 0x5ee948073c4f48b4L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bee4aL).optional(true).ordered(true).multiple(false).origin("6839076705052608692").done();
    b.aggregate("color", 0x5ee948073c4f48b5L).target(0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed69L).optional(true).ordered(true).multiple(false).origin("6839076705052608693").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTitulo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "Titulo", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed52L);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388690");
    b.version(3);
    b.property("tituloString", 0x5ee948073c4bed55L).type(PrimitiveTypeId.STRING).origin("6839076705052388693").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUbicacion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GCalendarInterpreter", "Ubicacion", 0x4a6101dd798a4af7L, 0x9cc1cbdd6558b662L, 0x5ee948073c4bed62L);
    b.class_(false, false, false);
    b.origin("r:c5149202-ab09-4801-b82a-d810bd981849(GCalendarInterpreter.structure)/6839076705052388706");
    b.version(3);
    b.property("stringUbicacion", 0x5ee948073c4bed64L).type(PrimitiveTypeId.STRING).origin("6839076705052388708").done();
    return b.create();
  }
}
